[package]
name = "scheduler_core"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.39", features = ["serde"] }
serde = { version = "1.0.217", features = ["derive"] }
uuid = { version = "1.12.0", features = ["serde"] }
