[package]
name = "scheduler_service"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio.workspace = true
dotenv.workspace = true
scheduler_core = { path = "../scheduler_core" }
axum = "0.8.1"
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true